/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario;

import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Toolkit;
//import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

public class frmIngresar extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresar
     */
    public frmIngresar() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtNombre.setBorder(new LineBorder(Color.black));
        txtEmail.setBorder(new LineBorder(Color.black));
        txtCurp.setBorder(new LineBorder(Color.black));
        txtWeb.setBorder(new LineBorder(Color.black));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblContraseña1 = new javax.swing.JLabel();
        lblContraseña2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("VALIDAR DATOS");

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        lblUsuario.setText("NOMBRE");

        txtNombre.setToolTipText("");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblContraseña.setText("E-MAIL");

        btnEntrar.setText("VALIDAR");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblContraseña1.setText("CURP");

        lblContraseña2.setText("WEB");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        txtWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWebActionPerformed(evt);
            }
        });
        txtWeb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWebKeyTyped(evt);
            }
        });

        txtCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpActionPerformed(evt);
            }
        });
        txtCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 118, Short.MAX_VALUE)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar)
                            .addComponent(lblContraseña1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblContraseña2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtEmail)
                                    .addComponent(txtCurp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtWeb))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraseña)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraseña1)
                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraseña2)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEntrar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if (Character.isLetter(letras)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    public void Nombre(String n) {
        int largo = n.length();
        if (largo < 3) {
            JOptionPane.showMessageDialog(null, "Por favor escribe minimo 3 caracteres");
            txtNombre.setBorder(new LineBorder(Color.red));
            txtEmail.setForeground(Color.red);
        } else if (n.matches("[a-zA-Z a-zA-Z]+")) {
            txtNombre.setBorder(new LineBorder(Color.green));

        } else {
            JOptionPane.showMessageDialog(null, "Por Favor solo coloca letras");
            txtNombre.setBorder(new LineBorder(Color.red));
            txtEmail.setForeground(Color.red);
        }

    }

    public void Correo(String c) {
        if ((c.length()) < 10) {
            JOptionPane.showMessageDialog(null, "Correo no valido, Escribe un correo Valido por favor");
            txtEmail.setBorder(new LineBorder(Color.red));
        } else if (c.substring(0, 1).matches("[a-zA-Z]")) {//***************PRIMER CARACTER 1***********************
            if (c.contains("@")) {
                String[] particion = c.split("@");
                if (particion[0].matches("[a-zA-Z0-9]+") || particion[0].matches("[a-zA-Z0-9_]+")) {//***************PARTE 1***********************
                    if (particion[1].contains(".com") || particion[1].contains(".COM")) {//***************PARTE 2***********************
                        String[] particionB = particion[1].split("\\.");
                        if (particionB[0].equals("outlook") || particionB[0].equals("gmail") || particionB[0].equals("hotmail") || particionB[0].equals("yahoo")
                                || particionB[0].equals("OUTLOOK") || particionB[0].equals("GMAIL") || particionB[0].equals("HOTMAIL") || particionB[0].equals("YAHOO")) {
                            if (particionB[1].equals("COM") || particionB[1].equals("com")) {//***************PARTE 3***********************
                                txtEmail.setBorder(new LineBorder(Color.green));
                                txtEmail.setForeground(Color.black);
                            } else {
                                JOptionPane.showMessageDialog(null, ".com con mayusculas o minusculas");
                                txtEmail.setBorder(new LineBorder(Color.red));
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "coloca por favor un cliente de correo electronico valido, ejemplo (correo002@hotmail.com)");
                            txtEmail.setBorder(new LineBorder(Color.red));
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "hace falta el .com");
                        txtEmail.setBorder(new LineBorder(Color.red));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, " caracteres no validos, ejemplo (correo002@hotmail.com)");
                    txtEmail.setBorder(new LineBorder(Color.red));
                }
            } else {
                JOptionPane.showMessageDialog(null, "hace falta el @");
                txtEmail.setBorder(new LineBorder(Color.red));
            }
        } else {
            JOptionPane.showMessageDialog(null, "no puedes colocar primero numeros, ejemplo (correo002@hotmail.com)");
            txtEmail.setBorder(new LineBorder(Color.red));
        }
    }

    public void curp(String cu) {
        String verificar = txtCurp.getText();
        String cadena;
        cadena = txtCurp.getText();//Obtener texto ingresado en la caja de texto y guardarlo en una variable
        int largo = cadena.length();//Obtener longitud de la cadena que se ingreso en la caja de texto
        if (largo != 18) {//si el largo de la cadena no es de 18 manda un mensaje de error
            txtCurp.setBorder(new LineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "EL CURP INGRESADO ES INCORRECTO");

        } else {//si el largo de la cadena si es de 18 entonces ejecuta este codigo         //partimos nuestra cadena en varias subcadenas para evaluar cada una de ellas
            String pt1 = cadena.substring(0, 4);//parte 1 Nombres
            String pt2 = cadena.substring(4, 10);//parte 2 fecha nac
            String pt3 = cadena.substring(10, 11);//parte 3 sexo (H o M)
            String pt4 = cadena.substring(11, 13);//parte 4 entidad federativa (2 caraceteres)
            String pt5 = cadena.substring(13, 16);//parte 5 primer consonante de primer apellido, primer consonante de segundo apellido, primer consonante de nombre 
            String pt6 = cadena.substring(16, 18);//parte 6 2 digitos al azar 

            //si la primera parte tiene letras entonces se sigue al siguiente if, si no manda un mensaje de error
            if (pt1.matches("[A-aZ-z]+")) {
                //si la segunda parte tiene numeros (por la fecha de nacimiento) entonces vamos bien y se sigue al siguiente if, si no manda un mensaje de error
                if (pt2.matches("[0-9]+")) {
                    //la tercera parte tiene que ser H o M por el sexo, si no es eso manda un mensaje de error
                    if (pt3.equals("M") || pt3.equals("H")) {
                        //la cuarta parte tiene que tener la clave de la entidad, si no es eso manda un mensaje de error    
                        if (pt4.equals("AS") || pt4.equals("BC") || pt4.equals("BS") || pt4.equals("CC") || pt4.equals("CS") || pt4.equals("CH") || pt4.equals("CL") || pt4.equals("CM") || pt4.equals("DF") || pt4.equals("DG") || pt4.equals("GT") || pt4.equals("GR") || pt4.equals("HG") || pt4.equals("JC") || pt4.equals("MC") || pt4.equals("MN") || pt4.equals("MS") || pt4.equals("NT") || pt4.equals("NL") || pt4.equals("OC") || pt4.equals("PL") || pt4.equals("QT") || pt4.equals("QR") || pt4.equals("SP") || pt4.equals("SL") || pt4.equals("SR") || pt4.equals("TC") || pt4.equals("TL") || pt4.equals("TS") || pt4.equals("VZ") || pt4.equals("YN") || pt4.equals("ZS")) {
                            if (pt5.matches("[A-Z]+")) {
                                //la quinta parte tiene que tener numeros, si no es eso manda un mensaje de error 
                                if (pt6.matches("[0-9]+")) {
                                    //si todo esta bien manda un mensaje de exito
                                    //JOptionPane.showMessageDialog(null, "EL CURP INGRESADO ES CORRECTO");
                                    txtCurp.setBorder(new LineBorder(Color.green));
                                } else {
                                    txtCurp.setBorder(new LineBorder(Color.red));
                                    JOptionPane.showMessageDialog(null, "los ultimos 2 caracteres deben ser numeros");
                                }
                            } else {
                                txtCurp.setBorder(new LineBorder(Color.red));
                                JOptionPane.showMessageDialog(null, "los caracteres deben ser  de 14 a 16");
                            }
                        } else {
                            txtCurp.setBorder(new LineBorder(Color.red));
                            JOptionPane.showMessageDialog(null, "la clave de entidad federativa, los caracteres son de 12 a 13");
                        }
                    } else {
                        txtCurp.setBorder(new LineBorder(Color.red));
                        JOptionPane.showMessageDialog(null, "Solo se puede ingresar H o M en el caracter 11 ");
                    }
                } else {
                    txtCurp.setBorder(new LineBorder(Color.red));
                    JOptionPane.showMessageDialog(null, "la fecha de nacimiento de  5 a 10 caracteres");
                }
            } else {
                txtCurp.setBorder(new LineBorder(Color.red));
                JOptionPane.showMessageDialog(null, "verifica los primeros 4 caracteres del nombre, por favor");

            }
        }
    }

    public void Web(String p) {
        if ((p.length()) < 9) {
            txtWeb.setBorder(new LineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Vuelve a escribir el enlace");
        } else {
            String[] split = p.split("\\.");
            //for (int i = 0; i < split.length; i++) {
            //    System.out.println("posicion " + i + split[i]);
            //}
            if (split[0].equals("www") || split[0].equals("WWW")) {
                if (split[1].matches("[a-zA-Z0-9]+")) {
                    if (split[2].equals("com") || split[2].equals("COM")) {
                        txtWeb.setBorder(new LineBorder(Color.green));

                    } else {
                        txtWeb.setBorder(new LineBorder(Color.red));
                        JOptionPane.showMessageDialog(null, "ingresa el COM por favor");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "ingresa el dominio de la pagina");
                    txtWeb.setBorder(new LineBorder(Color.red));
                }

            } else {
                JOptionPane.showMessageDialog(null, "ingresa correctamente el WWW ");
                txtWeb.setBorder(new LineBorder(Color.red));
            }

        }
    }


    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked


    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWebActionPerformed

    private void txtWebKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWebKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWebKeyTyped

    private void txtCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpActionPerformed

    private void txtCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            String cad = ("" + c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }

        if (txtCurp.getText().length() == 18) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

    }//GEN-LAST:event_txtCurpKeyTyped

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtEmail.setText("");
        txtCurp.setText("");
        txtWeb.setText("");

        txtNombre.setBorder(new LineBorder(Color.black));
        txtEmail.setBorder(new LineBorder(Color.black));
        txtCurp.setBorder(new LineBorder(Color.black));
        txtWeb.setBorder(new LineBorder(Color.black));

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if (txtNombre.getText().equals("") || txtEmail.getText().equals("") || txtCurp.getText().equals("") || txtWeb.getText().equals("")) {
            if (txtNombre.getText().equals("")) {
                txtNombre.setBorder(new LineBorder(Color.red));
            }
            if (txtEmail.getText().equals("")) {
                txtEmail.setBorder(new LineBorder(Color.red));
            }
            if (txtCurp.getText().equals("")) {
                txtCurp.setBorder(new LineBorder(Color.red));
            }
            if (txtWeb.getText().equals("")) {
                txtWeb.setBorder(new LineBorder(Color.red));
            }
            JOptionPane.showMessageDialog(null, "LLENA TODOS LOS CAMPOS");

            
        } else {
            
            String validar;
            validar = txtNombre.getText();
            Nombre(validar);

            String correo;
            correo = txtEmail.getText();
            Correo(correo);

            String val;
            val = txtCurp.getText();
            curp(val);

            String web;
            web = txtWeb.getText();
            Web(web);
            
           

            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblContraseña2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
